// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: tc/zone.proto

package tc

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Zone) Validate() error {
	if this.CreateTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreateTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreateTime", err)
		}
	}
	if this.UpdateTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdateTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdateTime", err)
		}
	}
	return nil
}
