// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: flamefatex/example/example.proto

package example

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
