// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: example-api/v2/example.proto

package v2

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/flamefatex/protos/goout/example"
	_ "github.com/flamefatex/protos/goout/common"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Example) Validate() error {
	if this.CreateTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.CreateTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("CreateTime", err)
		}
	}
	if this.UpdateTime != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.UpdateTime); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("UpdateTime", err)
		}
	}
	return nil
}
func (this *ExampleAllRequest) Validate() error {
	return nil
}
func (this *ExampleAllResponse) Validate() error {
	for _, item := range this.Examples {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Examples", err)
			}
		}
	}
	return nil
}
func (this *ExampleListRequest) Validate() error {
	return nil
}
func (this *ExampleListResponse) Validate() error {
	if this.Paging != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Paging); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Paging", err)
		}
	}
	for _, item := range this.Examples {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Examples", err)
			}
		}
	}
	return nil
}
func (this *ExampleGetRequest) Validate() error {
	return nil
}
func (this *ExampleGetResponse) Validate() error {
	if this.Example != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Example); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Example", err)
		}
	}
	return nil
}
func (this *ExampleDeleteRequest) Validate() error {
	return nil
}
